-- 用户
CREATE TABLE IF NOT EXISTS user (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    slot INTEGER DEFAULT 0,                   -- 饼干槽数
    email VARCHAR(320) NOT NULL UNIQUE,
    cookies VARCHAR(100) DEFAULT NULL UNIQUE, -- 饼干，按 cookie1;cookie2;cookie3;cookie4;cookie5; 排列
    password VARCHAR(32) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 1;

-- 串
CREATE TABLE IF NOT EXISTS segment (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER DEFAULT NULL,
    cookie CHAR(7) NOT NULL,
    warning TEXT DEFAULT NULL,
    channel VARCHAR(20) NOT NULL,
    sage BOOL DEFAULT FALSE,
    deleted BOOL DEFAULT FALSE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sage_time TIMESTAMP DEFAULT NULL,
    deleted_time TIMESTAMP DEFAULT NULL,

    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL
) AUTO_INCREMENT = 1;

-- 回复
CREATE TABLE IF NOT EXISTS reply (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER DEFAULT NULL,
    cookie CHAR(7) DEFAULT NULL,
    segment_id INTEGER NOT NULL,
    title TEXT DEFAULT NULL,
    text TEXT NOT NULL,
    image TEXT DEFAULT NULL,
    deleted BOOL DEFAULT FALSE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL,
    FOREIGN KEY (segment_id) REFERENCES segment(id) ON DELETE CASCADE
) AUTO_INCREMENT = 1;

-- 举报
CREATE TABLE IF NOT EXISTS tip_off (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER DEFAULT NULL,
    cookie CHAR(7) NOT NULL,
    reason TEXT NOT NULL,
    segment_id INTEGER NOT NULL,
    reply_id INTEGER NOT NULL,
    status INTEGER DEFAULT 0,

    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL,
    FOREIGN KEY (segment_id) REFERENCES segment(id) ON DELETE CASCADE,
    FOREIGN KEY (reply_id) REFERENCES reply(id) ON DELETE CASCADE
) AUTO_INCREMENT = 1;
